### ISSUE TITLE
(BUG) [Moviemade Version 1.3.0 ] When I click on open-source libraries, more text appears, which is very difficult to read

### ISSUE THREAD

**Issue by XAMIR555** [michaelbel/Moviemade#22]
#### Project Information
* Repository-----------:[Here](https://github.com/michaelbel/Moviemade)
* Project Name---------:  [Moviemade](https://play.google.com/store/apps/details?id=org.michaelbel.moviemade)
* Publisher------------:  [Michael Bely](https://github.com/michaelbel)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I click on open-source libraries, more txt should not be displayed that make trouble reading
and should be show the options should appear when I click the open-source library

#### Actual behavior

When I click on open-source libraries, more text appears, which is very difficult to read  you can see also in video 

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=org.michaelbel.moviemade)and open the application 
* Click the settings icon
* click on About
* click on the open-source libraries, option
* Note the Bug

* Browser/App version-: 1.3.0
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190708_161347](https://user-images.githubusercontent.com/49812927/60806105-f8716e00-a136-11e9-8377-b9a851cf7cc5.gif)

**Comment by michaelbel** [comment]
hmm, fragment transparency is broken

**Comment by XAMIR555** [comment]
Yes, and have you understood this bug ?  where the problem is encountered .

**Comment by michaelbel** [comment]
This bug is fixed, but not pushed in the repo.

**Comment by XAMIR555** [comment]
Okay and I'm waiting for your update version
